//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseOfTutorNew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseEnrolled
    {
        public CourseEnrolled()
        {
            this.ClassReports = new HashSet<ClassReport>();
            this.Fees = new HashSet<Fee>();
            this.Feenews = new HashSet<Feenew>();
        }
    
        public int id { get; set; }
        public string studentemail { get; set; }
        public string tutoremail { get; set; }
        public Nullable<int> courseid { get; set; }
        public string schedule { get; set; }
        public Nullable<int> coursestatus { get; set; }
        public string date { get; set; }
    
        public virtual ICollection<ClassReport> ClassReports { get; set; }
        public virtual Course Course { get; set; }
        public virtual Student Student { get; set; }
        public virtual Tutor Tutor { get; set; }
        public virtual ICollection<Fee> Fees { get; set; }
        public virtual ICollection<Feenew> Feenews { get; set; }
    }
}
