//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseOfTutorNew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public Course()
        {
            this.CourseEnrolleds = new HashSet<CourseEnrolled>();
            this.Fees = new HashSet<Fee>();
            this.Rates = new HashSet<Rate>();
            this.StudentCourseLists = new HashSet<StudentCourseList>();
            this.StudentRequests = new HashSet<StudentRequest>();
            this.TutorRequests = new HashSet<TutorRequest>();
            this.SemesterCourses = new HashSet<SemesterCourse>();
            this.TutorCourseLists = new HashSet<TutorCourseList>();
            this.TemporaryEnrolleds = new HashSet<TemporaryEnrolled>();
            this.StudentRequestTemporaryEnrollments = new HashSet<StudentRequestTemporaryEnrollment>();
        }
    
        public int courseid { get; set; }
        public string coursecode { get; set; }
        public string coursename { get; set; }
        public Nullable<int> coursefee { get; set; }
        public string coursefullname { get; set; }
    
        public virtual ICollection<CourseEnrolled> CourseEnrolleds { get; set; }
        public virtual ICollection<Fee> Fees { get; set; }
        public virtual ICollection<Rate> Rates { get; set; }
        public virtual ICollection<StudentCourseList> StudentCourseLists { get; set; }
        public virtual ICollection<StudentRequest> StudentRequests { get; set; }
        public virtual ICollection<TutorRequest> TutorRequests { get; set; }
        public virtual ICollection<SemesterCourse> SemesterCourses { get; set; }
        public virtual ICollection<TutorCourseList> TutorCourseLists { get; set; }
        public virtual ICollection<TemporaryEnrolled> TemporaryEnrolleds { get; set; }
        public virtual ICollection<StudentRequestTemporaryEnrollment> StudentRequestTemporaryEnrollments { get; set; }
    }
}
