//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseOfTutorNew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fee
    {
        public int id { get; set; }
        public string studentemail { get; set; }
        public string tutoremail { get; set; }
        public Nullable<int> courseid { get; set; }
        public Nullable<int> courseenrolledid { get; set; }
        public Nullable<int> amount { get; set; }
        public Nullable<int> feestatus { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual CourseEnrolled CourseEnrolled { get; set; }
        public virtual Student Student { get; set; }
        public virtual Tutor Tutor { get; set; }
    }
}
