//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseOfTutorNew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feenew
    {
        public int id { get; set; }
        public Nullable<int> courseenrolledid { get; set; }
        public Nullable<int> totalamount { get; set; }
        public Nullable<int> paidamount { get; set; }
        public Nullable<int> remainingamount { get; set; }
        public string status { get; set; }
        public Nullable<int> paid { get; set; }
    
        public virtual CourseEnrolled CourseEnrolled { get; set; }
    }
}
