//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseOfTutorNew.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class houseoftutorEntities : DbContext
    {
        public houseoftutorEntities()
            : base("name=houseoftutorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Admin> Admins { get; set; }
        public DbSet<ClassReport> ClassReports { get; set; }
        public DbSet<Course> Courses { get; set; }
        public DbSet<CourseEnrolled> CourseEnrolleds { get; set; }
        public DbSet<Fee> Fees { get; set; }
        public DbSet<NewReschedule> NewReschedules { get; set; }
        public DbSet<Rate> Rates { get; set; }
        public DbSet<Schedule> Schedules { get; set; }
        public DbSet<Student> Students { get; set; }
        public DbSet<StudentCourseList> StudentCourseLists { get; set; }
        public DbSet<StudentRequest> StudentRequests { get; set; }
        public DbSet<SubjectGroupName> SubjectGroupNames { get; set; }
        public DbSet<SubjectGroup> SubjectGroups { get; set; }
        public DbSet<Tutor> Tutors { get; set; }
        public DbSet<TutorRequest> TutorRequests { get; set; }
        public DbSet<SubjectFeeGroupName> SubjectFeeGroupNames { get; set; }
        public DbSet<Result> Results { get; set; }
        public DbSet<SemesterCourse> SemesterCourses { get; set; }
        public DbSet<studentNotification> studentNotifications { get; set; }
        public DbSet<tutorNotification> tutorNotifications { get; set; }
        public DbSet<TutorCourseList> TutorCourseLists { get; set; }
        public DbSet<setting> settings { get; set; }
        public DbSet<BlockedTutor> BlockedTutors { get; set; }
        public DbSet<Feenew> Feenews { get; set; }
        public DbSet<ScheduleChangeRequest> ScheduleChangeRequests { get; set; }
        public DbSet<TemporaryEnrolled> TemporaryEnrolleds { get; set; }
        public DbSet<StudentRequestTemporaryEnrollment> StudentRequestTemporaryEnrollments { get; set; }
        public DbSet<TempTakeClass> TempTakeClasses { get; set; }
        public DbSet<TempTakeClass1> TempTakeClass1 { get; set; }
        public IEnumerable<object> TempTakeClasss { get; internal set; }
    }
}
