//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseOfTutorNew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleChangeRequest
    {
        public int id { get; set; }
        public string tutoremail { get; set; }
        public string studentemail { get; set; }
        public Nullable<int> courseid { get; set; }
        public string slotTo { get; set; }
        public string slotFrom { get; set; }
        public string enrollDate { get; set; }
        public Nullable<int> status { get; set; }
    }
}
