//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseOfTutorNew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SemesterCourse
    {
        public SemesterCourse()
        {
            this.Results = new HashSet<Result>();
        }
    
        public int id { get; set; }
        public Nullable<int> semesterNo { get; set; }
        public Nullable<int> courseid { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual ICollection<Result> Results { get; set; }
    }
}
