//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseOfTutorNew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class setting
    {
        public int id { get; set; }
        public string email { get; set; }
        public Nullable<int> showClassReport { get; set; }
        public Nullable<int> showAbsents { get; set; }
        public Nullable<int> showRescheduleTutor { get; set; }
        public Nullable<int> showRescheduleStudent { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
