//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseOfTutorNew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemporaryEnrolled
    {
        public TemporaryEnrolled()
        {
            this.TempTakeClasses = new HashSet<TempTakeClass>();
            this.TempTakeClasses1 = new HashSet<TempTakeClass1>();
        }
    
        public int id { get; set; }
        public string studentemail { get; set; }
        public string tutoremail { get; set; }
        public Nullable<int> courseid { get; set; }
        public string schedule { get; set; }
        public Nullable<int> coursestatus { get; set; }
        public string date { get; set; }
        public string dateToEnd { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Student Student { get; set; }
        public virtual Tutor Tutor { get; set; }
        public virtual ICollection<TempTakeClass> TempTakeClasses { get; set; }
        public virtual ICollection<TempTakeClass1> TempTakeClasses1 { get; set; }
    }
}
