//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseOfTutorNew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempTakeClass
    {
        public int id { get; set; }
        public Nullable<int> tempId { get; set; }
        public Nullable<int> classesstatus { get; set; }
        public string classdate { get; set; }
        public string classslot { get; set; }
        public string classtime { get; set; }
        public string classTakenDate { get; set; }
    
        public virtual TemporaryEnrolled TemporaryEnrolled { get; set; }
    }
}
