//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseOfTutorNew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tutor
    {
        public Tutor()
        {
            this.CourseEnrolleds = new HashSet<CourseEnrolled>();
            this.Fees = new HashSet<Fee>();
            this.Rates = new HashSet<Rate>();
            this.StudentRequests = new HashSet<StudentRequest>();
            this.TutorRequests = new HashSet<TutorRequest>();
            this.tutorNotifications = new HashSet<tutorNotification>();
            this.TutorCourseLists = new HashSet<TutorCourseList>();
            this.BlockedTutors = new HashSet<BlockedTutor>();
            this.TemporaryEnrolleds = new HashSet<TemporaryEnrolled>();
            this.StudentRequestTemporaryEnrollments = new HashSet<StudentRequestTemporaryEnrollment>();
        }
    
        public string email { get; set; }
        public string name { get; set; }
        public string password { get; set; }
        public Nullable<int> semester { get; set; }
        public string contact { get; set; }
        public Nullable<double> cgpa { get; set; }
        public string image { get; set; }
        public string gender { get; set; }
        public Nullable<int> scheduleid { get; set; }
    
        public virtual ICollection<CourseEnrolled> CourseEnrolleds { get; set; }
        public virtual ICollection<Fee> Fees { get; set; }
        public virtual ICollection<Rate> Rates { get; set; }
        public virtual Schedule Schedule { get; set; }
        public virtual ICollection<StudentRequest> StudentRequests { get; set; }
        public virtual ICollection<TutorRequest> TutorRequests { get; set; }
        public virtual ICollection<tutorNotification> tutorNotifications { get; set; }
        public virtual ICollection<TutorCourseList> TutorCourseLists { get; set; }
        public virtual ICollection<BlockedTutor> BlockedTutors { get; set; }
        public virtual ICollection<TemporaryEnrolled> TemporaryEnrolleds { get; set; }
        public virtual ICollection<StudentRequestTemporaryEnrollment> StudentRequestTemporaryEnrollments { get; set; }
    }
}
